I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 175, in script
    n_nvl e2m2 "Hey! Welcome to the demo Eileen!"
Exception: Sayer 'n_nvl' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 175, in script
    n_nvl e2m2 "Hey! Welcome to the demo Eileen!"
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'n_nvl' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
code tyan 1.0
Thu Mar 20 18:13:08 2025
