I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/minigame/logic.rpy", line 321, in script
    $ minigame.run_puzzle(puzzle=puzzle)  # Запускаем головоломку
  File "game/minigame/logic.rpy", line 321, in <module>
    $ minigame.run_puzzle(puzzle=puzzle)  # Запускаем головоломку
NameError: name 'puzzle' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/minigame/logic.rpy", line 321, in script
    $ minigame.run_puzzle(puzzle=puzzle)  # Запускаем головоломку
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/minigame/logic.rpy", line 321, in <module>
    $ minigame.run_puzzle(puzzle=puzzle)  # Запускаем головоломку
NameError: name 'puzzle' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
code tyan 1.0
Sun Apr 20 21:02:47 2025
