I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 14, in script
    define you = Character("", callback=gen_voice)
  File "game/script.rpy", line 14, in <module>
    define you = Character("", callback=gen_voice)
NameError: name 'gen_voice' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 14, in script
    define you = Character("", callback=gen_voice)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 2222, in execute
    self.set()
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 2236, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 14, in <module>
    define you = Character("", callback=gen_voice)
NameError: name 'gen_voice' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
code tyan 1.0
Tue Feb 18 19:18:52 2025
