I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 69, in script
    scene city fadein 1.0
Exception: Image 'city' does not accept attributes 'fadein 1 .0'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 69, in script
    scene city fadein 1.0
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 1247, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'city' does not accept attributes 'fadein 1 .0'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
code tyan 1.0
Mon Mar  3 20:52:31 2025
